/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasiaspirasi;
import aplikasiaspirasi.services.Session;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.*;

/**
 *
 * @author Lenovo
 */
public class DashboardSiswa extends javax.swing.JFrame {

    /**
     * Creates new form DashboardSiswa
     */
    public DashboardSiswa() {

    initComponents();

    utils.Fonts.applyAgrandir(lblCopyrights);
    utils.Fonts.applyAgrandir(lblTitle);

    listPanel.setLayout(
        new BoxLayout(
            listPanel,
            BoxLayout.Y_AXIS
        )
    );

    jScrollPane.getVerticalScrollBar()
        .setUnitIncrement(16);

    jScrollPane.setBorder(null);

    jScrollPane.getViewport()
        .setBackground(Color.WHITE);
    dataNisn.setText(Session.getNis());
    loadAspirasi();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FullScreen = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblNisn = new javax.swing.JLabel();
        dataNisn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        btnAddAspirasi = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        listPanel = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        lblCopyrights = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FullScreen.setBackground(new java.awt.Color(255, 255, 255));

        Navbar.setBackground(new java.awt.Color(196, 149, 82));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Aplikasi Aspirasi");

        lblNisn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNisn.setForeground(new java.awt.Color(255, 255, 255));
        lblNisn.setText("NISN :");

        dataNisn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dataNisn.setForeground(new java.awt.Color(255, 255, 255));
        dataNisn.setText("012345678910");

        jButton1.setBackground(new java.awt.Color(196, 149, 82));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Log.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorder(null);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                        .addComponent(lblNisn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNisn))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                        .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataNisn)
                            .addComponent(lblNisn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        Content.setBackground(new java.awt.Color(255, 255, 255));

        btnAddAspirasi.setBackground(new java.awt.Color(196, 149, 82));
        btnAddAspirasi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnAddAspirasi.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAspirasi.setText("+ Tambahkan Aspirasi");
        btnAddAspirasi.setBorder(null);
        btnAddAspirasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAspirasiActionPerformed(evt);
            }
        });

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane.setBorder(null);
        jScrollPane.setForeground(new java.awt.Color(255, 255, 255));

        listPanel.setBackground(new java.awt.Color(255, 255, 255));
        listPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1880, Short.MAX_VALUE)
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(listPanel);

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addComponent(btnAddAspirasi, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane))
                .addContainerGap())
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnAddAspirasi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane))
        );

        Footer.setBackground(new java.awt.Color(196, 149, 82));

        lblCopyrights.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCopyrights.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyrights.setText("© 2026 Frieren Aspirations. All rights reserved");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(lblCopyrights)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblCopyrights)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout FullScreenLayout = new javax.swing.GroupLayout(FullScreen);
        FullScreen.setLayout(FullScreenLayout);
        FullScreenLayout.setHorizontalGroup(
            FullScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FullScreenLayout.setVerticalGroup(
            FullScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullScreenLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FullScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FullScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aplikasiaspirasi.services.Session.clear();;
        aplikasiaspirasi.Component.CustomPopup.showPopup(this, true, "Berhasil Logout :D", new NotLoginPage());
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddAspirasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAspirasiActionPerformed
         new aplikasiaspirasi.Component.AddAsp(this, true).setVisible(true);
         loadAspirasi();
    }//GEN-LAST:event_btnAddAspirasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel FullScreen;
    private javax.swing.JPanel Navbar;
    private javax.swing.JButton btnAddAspirasi;
    private javax.swing.JLabel dataNisn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblCopyrights;
    private javax.swing.JLabel lblNisn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel listPanel;
    // End of variables declaration//GEN-END:variables

private void loadAspirasi() {

    try (

        Connection conn =
            aplikasiaspirasi
            .services
            .Database
            .connect();

    ) {

        String sql =
            "SELECT * FROM sim_input_aspirasi " +
            "WHERE nis = ? " +
            "ORDER BY id_pelaporan DESC";

        PreparedStatement ps =
            conn.prepareStatement(sql);

        ps.setString(
            1,
            aplikasiaspirasi
            .services
            .Session
            .getNis()
        );

        ResultSet rs =
            ps.executeQuery();

        listPanel.removeAll();

        while(rs.next()) {

            String title =
                rs.getString("lokasi");

            String keterangan =
                rs.getString("ket");

            String status =
                "Menunggu";

            aplikasiaspirasi.Component.AspirasiCard card =
                new aplikasiaspirasi.Component.AspirasiCard(
                    title,
                    keterangan,
                    status
                );

            card.setAlignmentX(
                Component.CENTER_ALIGNMENT
            );

            listPanel.add(card);

            listPanel.add(
                Box.createVerticalStrut(15)
            );
        }

        listPanel.revalidate();
        listPanel.repaint();

    } catch(Exception e) {

        e.printStackTrace();
    }
}
}
