/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasiaspirasi;
import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class LoginPageAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginPageSiswa
     */
    public LoginPageAdmin() {
        initComponents();
        //SET UI
        utils.ImageUtils.setImageFitLabel(FrierenImage, "/imgs/Frieren-Cozy-Plush-Companion-Figure-PNG.png");
        utils.Fonts.applyAgrandir(Text1);
        utils.Fonts.applyAgrandir(Text2);
        utils.Fonts.applyAgrandir(lblLogin);
        utils.Fonts.applyAgrandir(lblUser);
        utils.Fonts.applyAgrandir(lblPw);
        
        txtUser.putClientProperty(
        "JTextField.placeholderText",
        "Masukkan usernamemu disini..."
        );
        
        txtPw.putClientProperty(
        "JTextField.placeholderText", 
        "Masukkan passwordmu disini..."
        );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fullscreen = new javax.swing.JPanel();
        FrierenImage = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPw = new javax.swing.JLabel();
        txtPw = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fullscreen.setBackground(new java.awt.Color(255, 255, 255));
        Fullscreen.setPreferredSize(new java.awt.Dimension(1904, 1044));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        Text1.setText("Frieren tidak akan melihat");

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        Text2.setText("passwordmu.");

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 0, 0));
        lblLogin.setText("Login (ADMIN)");

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 0, 0));
        lblUser.setText("Username :");

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 0, 0));

        lblPw.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPw.setForeground(new java.awt.Color(0, 0, 0));
        lblPw.setText("Password :");

        txtPw.setBackground(new java.awt.Color(255, 255, 255));
        txtPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPw.setForeground(new java.awt.Color(0, 0, 0));

        btnLogin.setBackground(new java.awt.Color(196, 149, 82));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FullscreenLayout = new javax.swing.GroupLayout(Fullscreen);
        Fullscreen.setLayout(FullscreenLayout);
        FullscreenLayout.setHorizontalGroup(
            FullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullscreenLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(FullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text2)
                    .addComponent(Text1)
                    .addGroup(FullscreenLayout.createSequentialGroup()
                        .addComponent(FrierenImage, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361)
                        .addGroup(FullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPw)
                            .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FullscreenLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblLogin)))))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        FullscreenLayout.setVerticalGroup(
            FullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullscreenLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(lblLogin)
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblPw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FullscreenLayout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(FrierenImage, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text2)
                .addGap(178, 178, 178))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fullscreen, javax.swing.GroupLayout.DEFAULT_SIZE, 1898, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fullscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (txtUser.getText().trim().isEmpty()
           || txtPw.getText().trim().isEmpty()
                ) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
        }
        
        String user = txtUser.getText();
        String pw = txtPw.getText();
        
        boolean success = 
                aplikasiaspirasi.services.LoginService.loginAdmin(user, pw);
        
        if (success) {
            aplikasiaspirasi.Component.CustomPopup.showPopup(this, true, "Login Berhasil :D", new DashboardAdmin());
            this.dispose();
        } else {
            aplikasiaspirasi.Component.CustomPopup.showPopup(this, false, "Login gagal :(", null);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrierenImage;
    private javax.swing.JPanel Fullscreen;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtPw;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
