/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package aplikasiaspirasi.Component;
import com.formdev.flatlaf.FlatClientProperties;
/**
 *
 * @author Lenovo
 */
public class AddAsp extends java.awt.Dialog {

    /**
     * Creates new form AddAsp
     */
    public AddAsp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //SET UI
        utils.Fonts.applyAgrandir(lblTitle);
        utils.Fonts.applyAgrandir(lblKategori);
        utils.Fonts.applyAgrandir(lblKeterangan);
        utils.Fonts.applyAgrandir(lblLokasi);
        utils.Fonts.applyAgrandir(cbAnonim);
        
       TextKeterangan.putClientProperty(
       FlatClientProperties.PLACEHOLDER_TEXT,
       "Masukkan keterangan aspirasi disini..."
       );
        
        TextLokasi.putClientProperty(
        "JTextField.placeholderText", 
        "Masukkan lokasi aspirasi disini..."
        );
        
        loadKategori();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbAnonim = new javax.swing.JCheckBox();
        lblLokasi = new javax.swing.JLabel();
        CBKategori = new javax.swing.JComboBox<>();
        lblKategori = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        TextLokasi = new javax.swing.JTextField();
        lblKeterangan = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextKeterangan = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbAnonim.setBackground(new java.awt.Color(255, 255, 255));
        cbAnonim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbAnonim.setForeground(new java.awt.Color(0, 0, 0));
        cbAnonim.setText("Anonim?");
        jPanel1.add(cbAnonim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        lblLokasi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLokasi.setForeground(new java.awt.Color(0, 0, 0));
        lblLokasi.setText("Lokasi :");
        jPanel1.add(lblLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        CBKategori.setBackground(new java.awt.Color(255, 255, 255));
        CBKategori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBKategori.setForeground(new java.awt.Color(0, 0, 0));
        CBKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(CBKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 710, 60));

        lblKategori.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKategori.setForeground(new java.awt.Color(0, 0, 0));
        lblKategori.setText("Kategori :");
        jPanel1.add(lblKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("Form Pengisian Aspirasi");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        TextLokasi.setBackground(new java.awt.Color(255, 255, 255));
        TextLokasi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextLokasi.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TextLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 710, 50));

        lblKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKeterangan.setForeground(new java.awt.Color(0, 0, 0));
        lblKeterangan.setText("Keterangan Aspirasi :");
        jPanel1.add(lblKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(196, 149, 82));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(null);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 310, 40));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        TextKeterangan.setBackground(new java.awt.Color(255, 255, 255));
        TextKeterangan.setColumns(20);
        TextKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextKeterangan.setRows(5);
        jScrollPane2.setViewportView(TextKeterangan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 710, 150));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void CBKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBKategoriActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
         submitAspirasi();
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddAsp dialog = new AddAsp(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBKategori;
    private javax.swing.JTextArea TextKeterangan;
    private javax.swing.JTextField TextLokasi;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox cbAnonim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

private void loadKategori() {

    try (

        java.sql.Connection conn =
            aplikasiaspirasi
            .services
            .Database
            .connect();

        java.sql.PreparedStatement ps =
            conn.prepareStatement(
                "SELECT * FROM sim_kategori"
            );

        java.sql.ResultSet rs =
            ps.executeQuery();

    ) {

        CBKategori.removeAllItems();

        while(rs.next()) {

            CBKategori.addItem(
                rs.getString("ket_kategori")
            );
        }

    } catch(Exception e) {

        e.printStackTrace();
    }
}

private void submitAspirasi() {

    String kategori =
        CBKategori.getSelectedItem()
        .toString()
        .trim();

    String lokasi =
        TextLokasi.getText()
        .trim();

    String keterangan =
        TextKeterangan.getText()
        .trim();

    if(
        lokasi.isEmpty() ||
        keterangan.isEmpty()
    ) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Data tidak boleh kosong!"
        );

        return;
    }

    try (

        java.sql.Connection conn =
            aplikasiaspirasi
            .services
            .Database
            .connect();

    ) {


        int idKategori = 0;

        java.sql.PreparedStatement psKategori =
            conn.prepareStatement(
                "SELECT id_kategori " +
                "FROM sim_kategori " +
                "WHERE ket_kategori = ?"
            );

        psKategori.setString(
            1,
            kategori
        );

        java.sql.ResultSet rsKategori =
            psKategori.executeQuery();

        if(rsKategori.next()) {

            idKategori =
                rsKategori.getInt(
                    "id_kategori"
                );

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Kategori tidak ditemukan!"
            );

            return;
        }


        java.sql.PreparedStatement psInput =
            conn.prepareStatement(
                "INSERT INTO sim_input_aspirasi " +
                "(nis, id_kategori, lokasi, ket) " +
                "VALUES (?, ?, ?, ?)",
                java.sql.Statement.RETURN_GENERATED_KEYS
            );

        psInput.setString(
            1,
            aplikasiaspirasi
            .services
            .Session
            .getNis()
        );

        psInput.setInt(
            2,
            idKategori
        );

        psInput.setString(
            3,
            lokasi
        );

        psInput.setString(
            4,
            keterangan
        );

        psInput.executeUpdate();

        int idPelaporan = 0;

        java.sql.ResultSet generatedKeys =
            psInput.getGeneratedKeys();

        if(generatedKeys.next()) {

            idPelaporan =
                generatedKeys.getInt(1);

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal mendapatkan ID aspirasi!"
            );

            return;
        }


        java.sql.PreparedStatement psAspirasi =
            conn.prepareStatement(
                "INSERT INTO sim_aspirasi " +
                "(id_aspirasi, status, id_kategori, feedback) " +
                "VALUES (?, ?, ?, ?)"
            );

        psAspirasi.setInt(
            1,
            idPelaporan
        );

        psAspirasi.setString(
            2,
            "Menunggu"
        );

        psAspirasi.setInt(
            3,
            idKategori
        );

        psAspirasi.setInt(
            4,
            0
        );

        psAspirasi.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aspirasi berhasil dikirim!"
        );

        dispose();

    } catch(Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Terjadi error:\n" + e.getMessage()
        );

        e.printStackTrace();
    }
}
}

