/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasiaspirasi.Component;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author Lenovo
 */
public class AspirasiCardAdmin extends javax.swing.JPanel {
    private int idAspirasi;
    private boolean initialized = false;
    public AspirasiCardAdmin(
    int id,
    String title,
    String keterangan,
    String status
) {

    initComponents();

    this.idAspirasi = id;

    setupUI();

    setData(
        title,
        keterangan,
        status
    );

    cbStatus.addActionListener(e -> {
         if(!initialized) {
        return;
       } 
        String selectedStatus =
            cbStatus.getSelectedItem()
            .toString();

        openFeedbackDialog(
            selectedStatus
        );
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShadowPanel = new javax.swing.JPanel();
        CardPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblKeterangan = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();

        ShadowPanel.setBackground(new java.awt.Color(255, 255, 255));

        CardPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("Judul");

        lblKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKeterangan.setForeground(new java.awt.Color(0, 0, 0));
        lblKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKeterangan.setText("Insert Keluh Kesah Here...");
        lblKeterangan.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cbStatus.setBackground(new java.awt.Color(255, 255, 255));
        cbStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbStatus.setForeground(new java.awt.Color(0, 0, 0));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout CardPanelLayout = new javax.swing.GroupLayout(CardPanel);
        CardPanel.setLayout(CardPanelLayout);
        CardPanelLayout.setHorizontalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 1571, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CardPanelLayout.setVerticalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ShadowPanelLayout = new javax.swing.GroupLayout(ShadowPanel);
        ShadowPanel.setLayout(ShadowPanelLayout);
        ShadowPanelLayout.setHorizontalGroup(
            ShadowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ShadowPanelLayout.setVerticalGroup(
            ShadowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShadowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShadowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardPanel;
    private javax.swing.JPanel ShadowPanel;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

private void setupUI() {

    utils.Fonts.applyAgrandir(lblTitle);
    utils.Fonts.applyAgrandir(lblKeterangan);

    setPreferredSize(
        new Dimension(1650, 140)
    );

    setMaximumSize(
        new Dimension(1650, 140)
    );

    setMinimumSize(
        new Dimension(1650, 140)
    );

    CardPanel.setBackground(Color.WHITE);

    ShadowPanel.setBackground(
        new Color(0,0,0,20)
    );

    ShadowPanel.setBorder(
        BorderFactory.createEmptyBorder(
            3,
            3,
            6,
            6
        )
    );
    cbStatus.removeAllItems();
    cbStatus.addItem("Menunggu");
    cbStatus.addItem("Proses");
    cbStatus.addItem("Selesai");
}

private void openFeedbackDialog(
    String status
) {

    JTextArea feedbackArea =
        new JTextArea(5,20);

    int result =
        JOptionPane.showConfirmDialog(
            this,
            new JScrollPane(feedbackArea),
            "Berikan Feedback",
            JOptionPane.OK_CANCEL_OPTION
        );

    if(result ==
        JOptionPane.OK_OPTION) {

        String feedback =
            feedbackArea.getText();

        saveStatus(
            status,
            feedback
        );
    }
}

private void saveStatus(
    String status,
    String feedback
) {

    try (

        Connection conn =
            aplikasiaspirasi
            .services
            .Database
            .connect();

        PreparedStatement ps =
            conn.prepareStatement(
                "UPDATE sim_aspirasi " +
                "SET status = ?, feedback = ? " +
                "WHERE id_aspirasi = ?"
            )

    ) {

        ps.setString(1, status);

        ps.setString(2, feedback);

        ps.setInt(3, idAspirasi);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(
            this,
            "Status berhasil diupdate!"
        );

    } catch(Exception e) {

        e.printStackTrace();
    }
}

private void setStatusColor(
    String status
) {

    switch(status) {
        case "Menunggu":
            cbStatus.setForeground(
                new Color(255,140,0)
            );
            break;
        case "Proses":
            cbStatus.setForeground(
                new Color(0,120,255)
            );
            break;

        case "Selesai":
            cbStatus.setForeground(
                new Color(0,170,80)
            );
            break;

        default:
            cbStatus.setForeground(
                Color.BLACK
            );
    }
}

public void setData(
    String title,
    String keterangan,
    String status
) {
    lblTitle.setText(title);
    lblKeterangan.setText(
        "<html>" + keterangan + "</html>"
    );
    cbStatus.setSelectedItem(status);
    setStatusColor(status);
    initialized = true;
}
}
