/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasiaspirasi.Component;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Lenovo
 */
public class AspirasiCard extends javax.swing.JPanel {

    /**
     * Creates new form AspirasiCard
     */
   public AspirasiCard() {

    initComponents();

    setupUI();

    setData(
        "Judul Aspirasi",
        "Isi keterangan aspirasi disini...",
        "Menunggu"
    );
}

public AspirasiCard(
    String title,
    String keterangan,
    String status
) {

    initComponents();

    setupUI();

    setData(
        title,
        keterangan,
        status
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShadowPanel = new javax.swing.JPanel();
        CardPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblKeterangazn = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        ShadowPanel.setBackground(new java.awt.Color(255, 255, 255));

        CardPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("Judul");

        lblKeterangazn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKeterangazn.setForeground(new java.awt.Color(0, 0, 0));
        lblKeterangazn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKeterangazn.setText("Insert Keluh Kesah Here...");
        lblKeterangazn.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblStatus.setText("Status");

        javax.swing.GroupLayout CardPanelLayout = new javax.swing.GroupLayout(CardPanel);
        CardPanel.setLayout(CardPanelLayout);
        CardPanelLayout.setHorizontalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKeterangazn, javax.swing.GroupLayout.PREFERRED_SIZE, 1571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CardPanelLayout.setVerticalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKeterangazn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ShadowPanelLayout = new javax.swing.GroupLayout(ShadowPanel);
        ShadowPanel.setLayout(ShadowPanelLayout);
        ShadowPanelLayout.setHorizontalGroup(
            ShadowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ShadowPanelLayout.setVerticalGroup(
            ShadowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShadowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShadowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardPanel;
    private javax.swing.JPanel ShadowPanel;
    private javax.swing.JLabel lblKeterangazn;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

private void setupUI() {

    utils.Fonts.applyAgrandir(lblTitle);
    utils.Fonts.applyAgrandir(lblKeterangazn);
    utils.Fonts.applyAgrandir(lblStatus);

    setPreferredSize(
        new Dimension(1650, 140)
    );

    setMaximumSize(
        new Dimension(1650, 140)
    );

    setMinimumSize(
        new Dimension(1650, 140)
    );

    CardPanel.setBackground(Color.WHITE);

    ShadowPanel.setBackground(
        new Color(0,0,0,20)
    );

    ShadowPanel.setBorder(
        BorderFactory.createEmptyBorder(
            3,
            3,
            6,
            6
        )
    );
}
private void setStatusColor(
    String status
) {

    switch(status) {
        case "Menunggu":
            lblStatus.setForeground(
                new Color(255,140,0)
            );
            break;
        case "Proses":

            lblStatus.setForeground(
                new Color(0,120,255)
            );
            break;
        case "Selesai":

            lblStatus.setForeground(
                new Color(0,170,80)
            );

            break;
        default:
            lblStatus.setForeground(
                Color.BLACK
            );
    }
}

public void setData(
    String title,
    String keterangan,
    String status
) {
    lblTitle.setText(title);
    lblKeterangazn.setText(
        "<html>" + keterangan + "</html>"
    );
    lblStatus.setText(
        "Status : " + status
    );
    setStatusColor(status);
}
}
