/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package aplikasiaspirasi.Component;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Lenovo
 */
public class CustomPopup extends java.awt.Dialog {

    /**
     * Creates new form CustomPopup
     */
    public CustomPopup(java.awt.Frame parent, boolean modal, boolean isSuccess, String message, java.awt.Frame nextFrame) {
        super(parent, modal);
        initComponents();
        
        //Setting UI
        utils.Fonts.applyAgrandir(Text);
        
        //Different outcome
        Text.setText(message);

        if (isSuccess) {
            btn.setText("Lanjutkan");
            utils.ImageUtils.setImageFitLabel(
            FrierenImgs,
            "/imgs/frieren-plush-character-toy.png");
        } else {
            btn.setText("Kembali");
            utils.ImageUtils.setImageFitLabel(
            FrierenImgs,
            "/imgs/Frieren-Imaginative-Plush-Figure-Creation-PNG.png");
        }

        btn.addActionListener(e -> {
            dispose();
            if (nextFrame != null) {
                nextFrame.setVisible(true);
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Text = new javax.swing.JLabel();
        FrierenImgs = new javax.swing.JLabel();
        btn = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Text.setForeground(new java.awt.Color(0, 0, 0));
        Text.setText("Login Berhasil!");
        Text.setToolTipText("");
        jPanel1.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));
        jPanel1.add(FrierenImgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 375, 350));

        btn.setBackground(new java.awt.Color(196, 149, 82));
        btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("jButton1");
        btn.setBorder(null);
        jPanel1.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 390, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CustomPopup dialog = new CustomPopup(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrierenImgs;
    private javax.swing.JLabel Text;
    private javax.swing.JButton btn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public static void showPopup(java.awt.Frame parent, boolean isSuccess, String message, java.awt.Frame nextFrame) {
    CustomPopup dialog = new CustomPopup(parent, true, isSuccess, message, nextFrame);
    dialog.setVisible(true);
}
}
